Repository AlbertoSH2021/APP-todolist-Grupal-Final, pull requests merged in 2022-02, with the labels that each got.

#24 agregar tareas
  admin/todolist-agregar.php
  admin/todolist-conexion.php
  admin/todolist.php
Labels: 00todolist

#25 edita tareas
  admin/todolist-editar.php
  admin/todolist-editar2.php
Labels: 00todolist

#26 funcionalidad de eliminar tareas
  admin/todolist-eliminar.php
  admin/todolist-eliminar2.php
Labels: 00todolist

#27 editar permisos de usuario
  admin/admin-permisos.php
Labels: 00OPErmisosUsuario

#28 registrarusuarios
  admin/InsertarUsuarios.php
Labels: 00Registrarusuario

#29 Backups
  admin/db.php
  admin/logica/conexion.php
  admin/logica/guardar.php
Labels: 00Base Datos, 00BackUP
