Repository AlbertoSH2021/APP-todolist-Grupal-Final, pull requests merged in 2022-01, with the labels that each got.

#5 Funcion:Inicio de sesion,conexcion a base de datos
  scripts/funciones.php
  scripts/iniciar-sesion.php
Labels: documentation, 00Login

#6 funciones para editar categorias de la tabla categorias
  scripts/actualizar-permisos.php
  scripts/editar-categoria.php
Labels: 00Categorias

#8 funcio de cerrar sesion
  scripts/cerrar-sesion.php
Labels: 00cerrarsesion

#9 lista de tareas por categoria
  admin/admin
  admin/categoria-eliminartarea.php
  admin/categoria-listadetareas.php
  admin/categoria-vertareas.php
Labels: 00todolist

#10 acceso por categoria y editar permiso por categoria
  admin/admin-categorias.php
  admin/admin-copiaseguridad.php
  admin/admin-editarCategoria.php
  admin/admin-editarPermisos.php
  admin/admin-index.php
  admin/admin-menu-lateral.php
Labels: 00Categorias, 00 editar categorias

#13 incorporación del chat Messenger culminado
  admin/messenger/chat.php
  admin/messenger/chat.sql
  admin/messenger/header.php
  admin/messenger/index.php
  admin/messenger/javascript/chat.js
  admin/messenger/javascript/login.js
  admin/messenger/javascript/pass-show-hide.js
  admin/messenger/javascript/signup.js
  admin/messenger/javascript/users.js
  admin/messenger/login.php
  admin/messenger/php/config.php
  admin/messenger/php/data.php
  admin/messenger/php/get-chat.php
  admin/messenger/php/images/1627784247descarga.jpg
  admin/messenger/php/images/1627784420images.jpg
  admin/messenger/php/images/1627787374images.jpg
  admin/messenger/php/images/1627789121images.jpg
  admin/messenger/php/images/1627789438images.jpg
  admin/messenger/php/images/1627790222HORAIO PERSONAL 2018-2.png
  admin/messenger/php/images/1628265284worker.png
  admin/messenger/php/images/1628267754beto.jpg
  admin/messenger/php/images/1641175714cf9a8cc7e82ce2f3f45a090c6e7b060a.jpg
  admin/messenger/php/images/1641176331aaaaa.png
  admin/messenger/php/images/1641179335logoheader1.png
  admin/messenger/php/images/1643038471betowhatsaapp.jpg
  admin/messenger/php/images/1643038570persona-de-libre-dedicacion.png
  admin/messenger/php/images/1643038621programmer-g7e3835663_1280.png
  admin/messenger/php/images/1643040292betowhatsaapp.jpg
  admin/messenger/php/insert-chat.php
  admin/messenger/php/login.php
  admin/messenger/php/logout.php
  admin/messenger/php/search.php
  admin/messenger/php/signup.php
  admin/messenger/php/users.php
  admin/messenger/style.css
  admin/messenger/stylee.css
  admin/messenger/unzipper.php
  admin/messenger/users.php
Labels: 00Interfaz, 00chats
